# scripts/clean_temp_files.py
"""
Delete temporary .tsv and .sqlite files generated by test scripts.

Usage (from project root):
  python -m scripts.clean_temp_files          # delete with confirmation
  python -m scripts.clean_temp_files --dry-run # list files without deleting
  python -m scripts.clean_temp_files --yes     # delete without confirmation
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

# Directories to skip entirely (no point scanning inside these)
SKIP_DIRS = {".venv", ".git", ".idea", "__pycache__", "node_modules"}

# File extensions to clean
TEMP_EXTENSIONS = {".tsv", ".sqlite"}


def find_temp_files(root: Path) -> list[Path]:
    """Walk *root* and return every file whose extension is in TEMP_EXTENSIONS."""
    found: list[Path] = []
    for dirpath, dirnames, filenames in os.walk(root):
        # prune skipped directories in-place so os.walk doesn't descend
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for name in filenames:
            if Path(name).suffix in TEMP_EXTENSIONS:
                found.append(Path(dirpath) / name)
    found.sort()
    return found


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Delete temporary .tsv and .sqlite files from the project.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="List files that would be deleted without actually deleting them.",
    )
    parser.add_argument(
        "--yes", "-y",
        action="store_true",
        help="Skip the confirmation prompt and delete immediately.",
    )
    args = parser.parse_args()

    project_root = Path(__file__).resolve().parents[1]
    files = find_temp_files(project_root)

    if not files:
        print("No temporary .tsv or .sqlite files found.")
        return

    print(f"Found {len(files)} temporary file(s):\n")
    for f in files:
        print(f"  {f.relative_to(project_root)}")

    if args.dry_run:
        print("\nDry run — nothing deleted.")
        return

    if not args.yes:
        answer = input("\nDelete these files? [y/N] ").strip().lower()
        if answer != "y":
            print("Aborted.")
            return

    deleted = 0
    for f in files:
        try:
            f.unlink()
            deleted += 1
        except OSError as e:
            print(f"  Could not delete {f.relative_to(project_root)}: {e}")

    print(f"\nDeleted {deleted} file(s).")


if __name__ == "__main__":
    main()
